USE alpha_pizza_db;
SET FOREIGN_KEY_CHECKS = 0;

-- This sql file loads dummy data from csv files into their corresponding table.
LOAD DATA LOCAL INFILE 'Database/csv_files/employee.csv'
INTO TABLE EMPLOYEE
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\r\n' 
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'Database/csv_files/customer.csv' 
INTO TABLE CUSTOMER
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\r\n' 
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'Database/csv_files/OrderPlacedBy.csv' 
INTO TABLE ORDERPLACEDBY
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\r\n' 
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'Database/csv_files/MakesBy.csv' 
INTO TABLE MAKESBY
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\r\n' 
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'Database/csv_files/OrderOverview.csv' 
INTO TABLE ORDEROVERVIEW
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\r\n' 
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'Database/csv_files/Contains.csv' 
INTO TABLE CONTAIN
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\r\n' 
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'Database/csv_files/OrderDetail_Item.csv' 
INTO TABLE ORDERDETAIL_ITEM
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\r\n' 
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'Database/csv_files/FilledBy.csv' 
INTO TABLE FILLEDBY
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\r\n' 
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'Database/csv_files/Item.csv'
INTO TABLE ITEM
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS
(ItemID, isAvailable, Price, ItemName, Category)
SET ItemStockQty = 0;

LOAD DATA LOCAL INFILE 'Database/csv_files/Order_Detail.csv' 
INTO TABLE ORDER_DETAIL
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\r\n' 
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'Database/csv_files/Ingredient.csv' 
INTO TABLE INGREDIENT
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\r\n' 
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'Database/csv_files/Supplier.csv' 
INTO TABLE SUPPLIER
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\r\n' 
IGNORE 1 ROWS;

SET FOREIGN_KEY_CHECKS = 1;
