USE alpha_pizza_db;
SET FOREIGN_KEY_CHECKS = 0;

-- This sql file loads dummy data from csv files into their corresponding table.
LOAD DATA INFILE 'employee.csv'
INTO TABLE EMPLOYEE
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n' 
IGNORE 1 ROWS;

LOAD DATA INFILE 'customer.csv' 
INTO TABLE CUSTOMER
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n' 
IGNORE 1 ROWS;

LOAD DATA INFILE 'OrderPlacedBy.csv' 
INTO TABLE ORDERPLACEDBY
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n' 
IGNORE 1 ROWS;

LOAD DATA INFILE 'MakesBy.csv' 
INTO TABLE MAKESBY
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n' 
IGNORE 1 ROWS;

LOAD DATA INFILE 'OrderOverview.csv' 
INTO TABLE ORDEROVERVIEW
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n' 
IGNORE 1 ROWS;

LOAD DATA INFILE 'Contains.csv' 
INTO TABLE CONTAIN
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n' 
IGNORE 1 ROWS;

LOAD DATA INFILE 'OrderDetail_Item.csv' 
INTO TABLE ORDERDETAIL_ITEM
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n' 
IGNORE 1 ROWS;

LOAD DATA INFILE 'FilledBy.csv' 
INTO TABLE FILLEDBY
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n' 
IGNORE 1 ROWS;

LOAD DATA INFILE 'Item.csv' 
INTO TABLE ITEM
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n' 
IGNORE 1 ROWS;

LOAD DATA INFILE 'Order_Detail.csv' 
INTO TABLE ORDER_DETAIL
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n' 
IGNORE 1 ROWS;

LOAD DATA INFILE 'Ingredient.csv' 
INTO TABLE INGREDIENT
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n' 
IGNORE 1 ROWS;

LOAD DATA INFILE 'Supplier.csv' 
INTO TABLE SUPPLIER
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n' 
IGNORE 1 ROWS;

SET FOREIGN_KEY_CHECKS = 1;
